# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '7.0'

target 'BoboGame-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoboGame-desktop
  pod 'Firebase'
  pod 'Firebase/Database'
end

target 'BoboGame-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoboGame-mobile
  pod 'Firebase'
  pod 'Firebase/Database'
end
